In [1]:
import cv2

In [2]:
img = cv2.imread("/Users/charithagadari/Downloads/000000000034.jpg")

In [4]:
print(img.shape)

(512, 512, 3)


In [5]:
print(img.dtype)

uint8


In [6]:
print(img.size)

786432


In [8]:
img_gray = cv2.imread("/Users/charithagadari/Downloads/000000000034.jpg", cv2.IMREAD_GRAYSCALE)

In [9]:
print(img)

[[[ 69 168 106]
  [ 57 154  92]
  [ 72 163 107]
  ...
  [ 20  44  14]
  [ 14  35  10]
  [ 18  37  12]]

 [[ 73 169 109]
  [ 57 151  94]
  [ 49 137  83]
  ...
  [ 24  46  17]
  [ 17  36   9]
  [ 19  35  11]]

 [[ 48 140  87]
  [ 51 141  88]
  [ 45 130  80]
  ...
  [ 36  54  25]
  [ 27  42  15]
  [ 22  37  10]]

 ...

 [[ 62 162 114]
  [ 64 165 114]
  [ 60 161 110]
  ...
  [ 49 167 114]
  [ 28 161 104]
  [ 12 152  91]]

 [[ 65 166 115]
  [ 63 164 112]
  [ 62 163 111]
  ...
  [ 55 168 118]
  [ 32 160 105]
  [ 18 154  96]]

 [[ 46 147  95]
  [ 42 143  91]
  [ 45 146  94]
  ...
  [ 33 144  94]
  [ 15 142  87]
  [ 52 185 129]]]


In [10]:
import numpy as np
img_norm = img.astype(np.float32)/255.0

In [11]:
print(img_norm)

[[[0.27058825 0.65882355 0.41568628]
  [0.22352941 0.6039216  0.36078432]
  [0.28235295 0.6392157  0.41960785]
  ...
  [0.07843138 0.17254902 0.05490196]
  [0.05490196 0.13725491 0.03921569]
  [0.07058824 0.14509805 0.04705882]]

 [[0.28627452 0.6627451  0.42745098]
  [0.22352941 0.5921569  0.36862746]
  [0.19215687 0.5372549  0.3254902 ]
  ...
  [0.09411765 0.18039216 0.06666667]
  [0.06666667 0.14117648 0.03529412]
  [0.07450981 0.13725491 0.04313726]]

 [[0.1882353  0.54901963 0.34117648]
  [0.2        0.5529412  0.34509805]
  [0.1764706  0.50980395 0.3137255 ]
  ...
  [0.14117648 0.21176471 0.09803922]
  [0.10588235 0.16470589 0.05882353]
  [0.08627451 0.14509805 0.03921569]]

 ...

 [[0.24313726 0.63529414 0.44705883]
  [0.2509804  0.64705884 0.44705883]
  [0.23529412 0.6313726  0.43137255]
  ...
  [0.19215687 0.654902   0.44705883]
  [0.10980392 0.6313726  0.40784314]
  [0.04705882 0.59607846 0.35686275]]

 [[0.25490198 0.6509804  0.4509804 ]
  [0.24705882 0.6431373  0.4392157 ]
